### PR TITLE
hyperparameter tuning tutorial

### PR DESCRIPTION
**Pull request by jtrieu2**
#### Description

This tutorial provides an example of how to tune a Random Forest classifier using GridSearchCV on the MNIST dataset. This tutorial will be added to Sklearn's documentation on hyperparameter tuning.

#### Steps/Code to Reproduce
link to code: https://github.com/jtrieu2/scikit-learn/blob/master/doc/tutorial/hyperparameter_tuning_random_forest/hyperparameter_tuning_random_forest.ipynb

### CODE REVIEW

**Comment by bdpedigo** [comment]
- remove the parts about "assume gaussian" for the standard scaler. The scaler itself is just computing a mean and standard deviation, doesnt have to be gaussian.

**Comment by bdpedigo** [comment]
- I am confused by formatting: why do you have markdown blocks, code cells that are rendered not as cells (does this make sense?), and quote cells in markdown, and real code cells? I find it confusing bouncing between all 4 of these (with the exception of the occasional quote, I would stick to just markdown cells and code block cells.) 

- in randomized search cv description "Below is the grid of all possible parameter combinations that are supplied to the Random Forest model" does not sound quite right to me, makes it sound like you are doing a grid search again. 
- minor typo, should say 2. instead of 1. for randomized search section
- are you just including screenshotted figures/table because it takes so long to run? 
- I am confused why you show those results in the beginning

**Comment by jtrieu2** [comment]
- Code block cells that are rendered as code block cells have now been deleted.
- Results section has been moved to the end. Summary of results were provided because the cells take long to run. Should it be removed entirely?

**Comment by bdpedigo** [comment]
@jtrieu2 I think you missed one of my comments above (minor typo, 1 -> 2) 

can you change the name of this file, remove the _edit thing, make the title lowercase, make the title of the file a bit more specific

After that I will merge! We may want to revisit having the images in that folder like they are now but for now I think it is fine. 

did i ever tell you about how to get the seaborn heatmap to render properly? It's just a matplotlib version thing

**Comment by jtrieu2** [comment]
@bdpedigo 
1. for some reason, i can't the numbering to show up properly so i ended up changing the format to bolded text instead of numbering. 
2. no, does that mean i need to install a different version of matplotlib? can you clarify further on what you mean by matplotlib version? thanks!

**Comment by bdpedigo** [comment]
@jtrieu2 there are two notebooks in this PR, can you remove one of them, or are they different things?

**Comment by jtrieu2** [comment]
@bdpedigo, it's deleted now. I didn't realize I had put the same notebook in two places.

**Comment by bdpedigo** [comment]
Great it's as good as merged! Just can't do it from my phone right now lol

**Comment by bdpedigo** [comment]
Nice work!

**Pull request merged**
