### PR TITLE
Comparing the performance of different clustering algorithms on toy datasets on adding high dimensional gaussian noise

### PR DESCRIPTION
**Pull request by sree0917**
Aim: Analyzing how the performance of different clustering algorithms for different datasets change on adding noise with different dimensions:

This demo is a Jupyter Notebook documentation describing the effect of the addition of different dimensions of noise on a dataset. Here different types of synthetic datasets are generated on which the experiment is performed. To these datasets Gaussian noise of different dimensions are added, and the performance of each clustering algorithm is measured after noise addition. This is repeated for noise with different variances.

Output: The plots that compare the effect of varying noise dimensions on different clustering algorithms for each of the datasets. In this set of subplots, the variance of the added noise changes along the column and the dataset changes along the row.

Link to the demo: https://github.com/sree0917/scikit-learn/blob/master/examples/cluster/comparison_of_clustering_algorithms.ipynb

### CODE REVIEW

**Comment by bdpedigo** [comment]
I believe I asked to remove tick labels and ticks and axes labels for the dataset plots. other than that looking good

**Comment by sree0917** [comment]
I have made the changes now. Thanks.

**Comment by bdpedigo** [comment]
@sree0917 nice work, plots look great. 

only thing left - I just don't agree with comments about DBSCAN, it looks like it alway sucks? Honestly most of that interpretation at the end isn't necessary, the plot really speaks for itself. So i'd say either take that part out, or remove the stuff about DBSCAN or make it agree more with what the plots are showing

well done! i will merge after you address that one comment

**Comment by sree0917** [comment]
I have kept it for running after making necessary changes. Thank you so much for the feedback.

**Comment by sree0917** [comment]
@bdpedigo I have removed the result interpretation part.

**Comment by sree0917** [comment]
Sorry, there were some typos  I had to correct. I have uploaded the final version of the notebook.

**Review by bdpedigo — COMMENTED** [review]
Where did the plots go?

**Comment by sree0917** [comment]
Is it not getting displayed? I am confused because I am able to view the final plot.

**Comment by bdpedigo** [comment]
@sree0917 i see it now, weird. 

Nice work!

**Comment by sree0917** [comment]
Thanks!

**Pull request merged**
